title: Ernst.site
logo: 
description: <br>Deputy Engineering Project Manager at Lockheed Martin <br><br> B.S. Electrical Engineering <br><br> B.A. German
 <br><br> Please See - <a href="http://www.ernst.lighting">www.ernst.lighting</a>
show_downloads: FALSE
google_analytics: 
google_analytics: 
theme: jekyll-theme-minimal
