title: Ernst.site
logo: 
description: <br>Element Integration & Test Engineer at Lockheed Martin <br><br> B.S. Electrical Engineering <br><br> B.A. German 
<br><br> Previously a Varsity Student Athlete at Lehigh University
<br><br> Please See - <a href="http://www.ernst.lighting">www.ernst.lighting</a>
show_downloads: FALSE
google_analytics: 
google_analytics: 
theme: jekyll-theme-minimal
